---
- hosts: localhost
  connection: local

  tasks:
  - name: Create ec2 Instances
    amazon.aws.ec2_instance:
      name: "{{ item.name }}"
      key_name: "aws_login_demo"
      instance_type: t2.micro
      security_group: default
      region: us-east-1
      aws_access_key: "{{ec2_access_key}}"
      aws_secret_key: "{{ec2_secret_key}}"
      network: 
        assign_public_ip: true
      image_id: "{{ item.image }}"

      #instead of using normal way as ansible will not create another instance with same id so we can use 
      #Idempotence in Ansible is a feature that allows users to run tasks multiple times without changing the final outcome. This is because Ansible modules check if the desired state has already been achieved and exit if it has.

    loop: 
      - { image: "ami-04b4f1a9cf54c11d0", name: "manage-node-1" } # Update AMI ID according 
      - { image: "ami-04b4f1a9cf54c11d0", name: "manage-node-2" } # to your account
      - { image: "ami-04b4f1a9cf54c11d0", name: "manage-node-3" } 
