---
- hosts: all
  become: true

  tasks:
    - name: shutdown ubuntu instances
      ansible.builtin.command:  /sbin/shutdown -t now 
      #built in command to shutdown instance on all instances
      # to avoid this we can use when codition in ansible
      when:
        ansible_facts['os_family'] == "Debian"



        
   # - name: print all ansible gather facts
   #   ansible.builtin.debug:
   #     var: ansible_facts
        
